apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-uploads
  namespace: pvcai-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: isilon
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-data
  namespace: pvcai-workspace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: isilon

